version: '3.8'

services:

  web:
    build:
      context: ./
      dockerfile: nginxed.Dockerfile
    ports:
      - 80:5000
    env_file:
      - .env
    volumes:
      - ../:/var/www/html
    depends_on:
      - db
    links:
      - db

  db:
    image: 'mysql:8.0.20'
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: 'secret'
      MYSQL_USER: '${DB_USERNAME}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
      MYSQL_DATABASE: '${DB_DATABASE}'
    ports:
      - 3306:3306
    volumes:
      - $LOCAL_DB_PATH:/var/lib/mysql